### ISSUE TITLE
"Import Selected/Most Recent" ops report file read errors

### ISSUE THREAD

**Issue by ghost** [hnordquist/Radiation-Review#1]
Unfortunately we (Wulf, Lee, Josef) found a problem with Rad Review.
With the latest version (3.2.1.0) you can only use "import all".
"Import Selected" reports that the file cannot be read
"Import Most Recent" reports that the file header cannot be read
Could you please have a look at this or let us know if this is a known issue?

**Comment by hnordquist** [comment]
I thought this was fucked up for a while but most no one uses it.
