### ISSUE TITLE
Signed VBF files are not read under some circumstances

### ISSUE THREAD

**Issue by ghost** [hnordquist/Radiation-Review#2]
1st report: (Wulf) RadReview starts to process the first file and never continues/finishes.
2nd report: The "inspection window" pops up and after confirmation the software does not react anymore.

**Comment by ghost** [comment]
Might be the same underlying issue as the observed issue where a subdir with data timestamps overlapping existing  data hangs or loop

**Comment by hnordquist** [comment]
This was the problem I fixes. Lemme make sure you've got latest.

**Comment by hnordquist** [comment]
Hey, also check that you are using latest Check_Signature dll
